FROM ubuntu:20.04
ENV TZ=Asia/kolkata \
    DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install tzdata
RUN apt-get update
RUN apt-get install -y mysql-server
RUN mysql_secure_installation
RUN apt install -y php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip php php-mysql
RUN curl -O https://wordpress.org/latest.tar.gz
RUN tar -xvzf latest.tar.gz

RUN apt-get install nginx -y
RUN apt-get install curl -y
RUN mkdir -p /var/www/abdhesh/tech

RUN ln -s /etc/nginx/sites-available/abdhesh /etc/nginx/sites-enabled/
EXPOSE 80:80
CMD echo 'hello world'
